#!/usr/bin/python2 -S
# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

import site
import traceback
import codecs
import os
import sqlite3
#import pprint
import subprocess


import  jqdatasdk as jq
import  pandas as pd

import db_operator
import data_struct 
import jq_acc
import data_fetcher


MY_NAME='mf'

# 工具入口

def print_usage( argv0 = MY_NAME ):
    print "Usage:"



def list_all_sec():
    r = jq.get_all_securities()
    pd.set_option('display.max_rows', len(r))
    print r
    pd.reset_option('display.max_rows')


# 处理 'fetch' 子命令
def handle_fetch( argv, argv0 = MY_NAME ): 
    try:
        # make sure DB exists
        conn = db_operator.get_db_conn()
        conn.close()

        # get db engine
        engine = db_operator.get_db_engine()

        df =  data_fetcher.get_annual_balancesheet('000001.XSHE', '2017')
        #print df

        db_operator. save_balance_df_to_db(engine, df)
        
        df =  data_fetcher.get_valuation('000001.XSHE', '2017-12-31')
        db_operator. save_valuation_df_to_db (engine, df)


        # real stuff
        

    except  Exception as e:
        
        (t, v, bt) = sys.exc_info()
        traceback.print_exception(t, v, bt)
        print
        print e
        return 1 
    finally:
        pass


    return 0



# 处理 'list' 子命令
def handle_list( argv, argv0 = MY_NAME ): 
    try:
        # connect to DB 
        conn = db_operator.get_db_conn()
        dbcur = conn.cursor()

        # real stuff
        list_all_sec()
        
        # DB clean up
        conn.commit()

    except  Exception as e:
        
        (t, v, bt) = sys.exc_info()
        traceback.print_exception(t, v, bt)
        print
        print e
        return 1 
    finally:
        dbcur.close()
        conn.close()

    return 0


def make_sure_working_dir():
    r = subprocess.call([ "mkdir"
            , "-p"
            , data_struct.WORKING_DIR 
            ])

    if 0 != r:
        raise Exception("Failed to make '%s'" % data_struct.WORKING_DIR );


def main(): 
    
    i = len(sys.argv)
    if ( i < 2 ):
        print_usage()
        return 1

    jq.auth(jq_acc.JQ_USERNAME ,jq_acc.JQ_PASSWORD )

    make_sure_working_dir()

    sub_command = sys.argv[1]

    if ('import' == sub_command ):
        return handle_import ( sys.argv[2:] )   
    elif ('fetch' == sub_command ):
        return handle_fetch ( sys.argv[2:] )  
    elif ('list' == sub_command ):
        return handle_list ( sys.argv[2:] )  
    elif ('help' == sub_command ):
        print_usage()
        return 1
    else:
        print "\n无效的‘子命令’ -- %s\n" % ( sub_command, )
        print_usage()
        return 1
  
    return 0

if __name__ == "__main__":
    r = main()
    sys.exit(r)


